# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/management_system
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=developer
spring.datasource.password=12345678

# JPA | HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false